# Generated by Django 5.1.1 on 2026-03-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaysubscriber',
            name='last_birthday_notified_on',
            field=models.DateField(blank=True, null=True, verbose_name='Последнее уведомление о дне рождения'),
        ),
    ]
